### PR TITLE
Add lightgun & update libretro

### PR DESCRIPTION
**Pull request by Wiimpathy**
It seems ok in general at least for the Wii. 
I've also tried to remove some unecessary neogeo stuff since there's already fbalpha2012_neogeo for that.

### CODE REVIEW

**Comment by dankcushions** [comment]
i don’t really see the reason to remove neogeo stuff. if anything it seems pointless to have a separate core for neogeo?

**Comment by barbudreadmon** [comment]
I don't think this PR remove any neogeo stuff ? If anything, it's mainly backporting a lot of input related stuff from FBNeo.

PS : i'm not sure there is much point in backporting joyprocess stuff if you don't deploy it in the game drivers.

**Comment by Wiimpathy** [comment]
I've just implemented Lightgun support for the Wii : https://github.com/libretro/RetroArch/pull/9470
Without this backporting stuff, lightgun wasn't working at all. Now, some lightgun games seems to work. This was the only goal of this pull request.

Why a seperate NeoGeo core? It's for low specs platform such as the Wii. There's not much RAM, that's why there are seperate fba2012 capcom and neogeo cores.

**Comment by twinaphex** [comment]
I can understand why he excluded Neo Geo. On Wii you need all the RAM you can get, and stripping those parts out can definitely result in bigger ROMs being able to be loaded. This is especially important for Gamecube which has even fewer RAM, and it reuses the same codebase as the Wii port.

**Comment by twinaphex** [comment]
Hmm, I guess I didn't fully understand that by the removal of Neo Geo, apparently it was removed for all platforms? This is not desirable. Can we instead only conditionally remove it for GEKKO builds @Wiimpathy ? Can you change/fix this in a followup PR? It's kinda a drag that this got removed this way, but I'm fine with it being stripped out of the Gamecube/Wii cores since I know RAM is not at a premium.

**Comment by barbudreadmon** [comment]
Again, i don't see anything removing neogeo support in this PR, it's just a huge backport from FBNeo, basically the old libretro port was trashed to use mine. I get the feeling you'll get complaints though : i trashed "macro support in core options" some time ago and i think some ppl were using fbalpha2012 because of this, now it's gone from both cores, not that it should have been there in the first place (it should be a frontend feature)

**Comment by Wiimpathy** [comment]
Yeah, sorry for the confusion, I thought some essential neogeo parts were removed. It's still working for other platforms! 
I haven't tested a linux build untill now. Thanks to your fix @twinaphex .
And as it is, it doesn't interfere with the GEKKO build either.

@barbudreadmon I admit that with so many things to test in different emulators for this lightgun feature, I have overlooked what you say about the macro and input in general in fba.

**Comment by twinaphex** [comment]
Some platforms need to be fixed now after this PR was merged -

fbalpha2012: [Status: fail] [recipes/android/cores-android] [Finished: 2019-09-16 14:14:14.145501+00:00] [http://paste.libretro.com/161183]

This used to compile on Android.

**Comment by Wiimpathy** [comment]
I know nothing about android build but it seems that **retro_common.cpp** and **retro_input.cpp** aren't compiled. 
Maybe these files just need to be added to Android.mk : https://github.com/libretro/fbalpha2012/blob/master/svn-current/trunk/projectfiles/libretro-android/jni/Android.mk#L142

**Pull request merged**
