### PR TITLE
Add 5 ROM drivers from FBA 0.2.97.42.

### PR DESCRIPTION
**Pull request by SumavisionQ5**

### CODE REVIEW

**Comment by dankcushions** [comment]
what are all these? why not just use https://github.com/libretro/fbalpha

**Comment by SumavisionQ5** [comment]
They are removed from FBA 0.2.97.43 due to the conflict between hacker and FBA's devs, so I think better to keep them in an old FBA build.

**Comment by fr500** [comment]
but this core is 0.2.97.28 or something like that....

**Comment by SumavisionQ5** [comment]
@fr500 These 5 hacked ROM drivers were permantly removed from FBA due to the ROM hacker's insult to FBA developers. But indeed these hacked ROM are worth playing. And adding these drivers back to latest FBA would cause troubles when bumping with new versions of FBA. Now then fba2012 is less active, why not add these drivers to it just like we did to MAME2003 plus.

**Pull request closed without merging**
