### PR TITLE
Fix for NEO GEO KOF2003

### PR DESCRIPTION
**Pull request by netux79**
copied from up-to-date fbalpha core: https://github.com/libretro/fbalpha/blob/master/src/burn/drv/neogeo/d_neogeo.cpp

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi @netux79 , nice to see you again and thanks for your contribution!

**Comment by netux79** [comment]
Hi @twinaphex . Yeah, it's more difficult for me now I have wife and a baby but I will here from time to time with small contributions to this great Libretro project  :) .

**Comment by twinaphex** [comment]
Good to hear you still enjoy the project. Not sure if you still use the Wii but it would be possible to add stuff like resolution switching now that we have the mechanisms for it, we would just need a Wii implementation. It's completely up to you, though - just thought i'd mention it. You could always talk to @alphanu1 for help on how to add it.

**Comment by netux79** [comment]
Thanks twinaphex for the invitation. I would like to help, but for now I have very few spare time. However, it would be nice to have resolution switching on Wii. I might give it a try later. For now I just will be doing some pull request of some small fixes I have done for some of the libretro cores.

**Comment by alphanu1** [comment]
@netux79

If you point me in the right place for switching the resolution on the Wii I can implement it.

**Pull request merged**
